@startuml AbstractFactory
skinparam linetype ortho
'skinparam linetype polyline

abstract class AbstractFactory.XMLBuilder {
	+{abstract}BuildDocument()
	+{abstract}BuildElement(string)
	+{abstract}BuildAttribute(string, string)
	+{abstract}BuildText(string)
	+GetDOM()
	+popProbe()
}

class ConcreteFactory.NodeXMLBuilder {
	#Document_Impl* _currentDOM
	+BuildDocument()
	+BuildElement(string)
	+BuildAttribute(string, string)
	+BuildText(string)
	+GetDOM()
	+popProbe()
}

class ConcreteFactory.MinimalNodeXMLBuilder {
	+BuildDocument()
}

class ConcreteFactory.PrettyNodeXMLBuilder {
	+BuildDocument()
}

abstract class AbstractProduct.Document_Impl {
	+createElement(...)
	+createTextNode(...)
	+createAttribute(...)
}

class ConcreteProduct.PrettyDocument_Impl {
	+createElement(...)
	+createTextNode(...)
	+createAttribute(...)
}

abstract class AbstractProduct.Element_Impl {
	+serialize_indentation(...)
	+serialize_newLine(...)
}

class ConcreteProduct.PrettyElement_Impl {
	+serialize_indentation(...)
	+serialize_newLine(...)
}

abstract class AbstractProduct.Attr_Impl {
	+serialize_indentation(...)
	+serialize_newLine(...)
}

class ConcreteProduct.PrettyAttr_Impl {
	+serialize_indentation(...)
	+serialize_newLine(...)
}

abstract class AbstractProduct.Text_Impl {
	+serialize_indentation(...)
	+serialize_newLine(...)
}

class ConcreteProduct.PrettyText_Impl {
	+serialize_indentation(...)
	+serialize_newLine(...)
}

class Client.XMLTokenizer {
	+construct(...)
}

note "ConcreteFactory further delegates ConcreteProduct creation to these Factory Methods" as N1

AbstractFactory.XMLBuilder <|-down- ConcreteFactory.NodeXMLBuilder
ConcreteFactory.NodeXMLBuilder <|-left- ConcreteFactory.MinimalNodeXMLBuilder
ConcreteFactory.NodeXMLBuilder <|-right- ConcreteFactory.PrettyNodeXMLBuilder
ConcreteFactory.MinimalNodeXMLBuilder *--> AbstractProduct.Document_Impl
ConcreteFactory.MinimalNodeXMLBuilder ..> AbstractProduct.Element_Impl
ConcreteFactory.MinimalNodeXMLBuilder ..> AbstractProduct.Attr_Impl
ConcreteFactory.MinimalNodeXMLBuilder ..> AbstractProduct.Text_Impl
ConcreteFactory.PrettyNodeXMLBuilder *--> ConcreteProduct.PrettyDocument_Impl
ConcreteFactory.PrettyNodeXMLBuilder ..> ConcreteProduct.PrettyElement_Impl
ConcreteFactory.PrettyNodeXMLBuilder ..> ConcreteProduct.PrettyAttr_Impl
ConcreteFactory.PrettyNodeXMLBuilder ..> ConcreteProduct.PrettyText_Impl
AbstractProduct.Document_Impl <|-- ConcreteProduct.PrettyDocument_Impl
AbstractProduct.Document_Impl .down. N1
N1 .up. ConcreteProduct.PrettyDocument_Impl
AbstractProduct.Element_Impl <|-- ConcreteProduct.PrettyElement_Impl
AbstractProduct.Attr_Impl <|-- ConcreteProduct.PrettyAttr_Impl
AbstractProduct.Text_Impl <|-- ConcreteProduct.PrettyText_Impl
Client.XMLTokenizer -right-> AbstractFactory.XMLBuilder

@enduml