@startuml FactoryMethod
'skinparam linetype ortho
skinparam linetype polyline

interface Product.Attr {
    int i
    int x
}
interface Product.Element {
    int i
}
interface Product.Text {
    int i
}
class ConcreteProduct.Attr_Impl {
    int i
}
class ConcreteProduct.Element_Impl {
    int i
}
class ConcreteProduct.Text_Impl {
    int i
}
interface Creator.Document {
    int i
    +[FactoryMethod] createAttribute(...)   : Attr
    +[FactoryMethod] createElement(...)     : Element
    +[FactoryMethod] createTextNode(...)    : Text
}
class ConcreteCreator.Document_Impl {
    +[FactoryMethod] createAttribute(...)   : Attr
    +[FactoryMethod] createElement(...)     : Element
    +[FactoryMethod] createTextNode(...)    : Text
}

Product.Attr        <|..    ConcreteProduct.Attr_Impl
Product.Element     <|..    ConcreteProduct.Element_Impl
Product.Text        <|..    ConcreteProduct.Text_Impl
Creator.Document    <|..    ConcreteCreator.Document_Impl
ConcreteProduct.Attr_Impl     <-    ConcreteCreator.Document_Impl   : .
ConcreteProduct.Element_Impl  <-    ConcreteCreator.Document_Impl   : instantiate
ConcreteProduct.Text_Impl     <-    ConcreteCreator.Document_Impl   : instantiate
@enduml